14
dellydel/med-manage-web pull request #63
Opened 2024-10-14 19:47 UTC by osaosula

Add new patient UI

2024-10-14 22:04 UTC, BorisLaboratory requested changes
Looks good but with a few observations . See comments

2024-10-14 22:04 UTC, BorisLaboratory commented on src/pages/AddPatient.jsx
> +              </Grid>{" "}
There is unwanted code block

2024-10-14 22:04 UTC, BorisLaboratory commented on src/pages/AddPatient.jsx
> +              </Grid>{" "}
There is unwanted code block

2024-10-14 22:04 UTC, BorisLaboratory commented on src/pages/AddPatient.jsx
> +              </Grid>{" "}
There is unwanted code block

2024-10-15 01:46 UTC, osaosula commented on src/pages/AddPatient.jsx
> +              </Grid>{" "}
Fixed

2024-10-15 01:47 UTC, osaosula commented on src/pages/AddPatient.jsx
> +              </Grid>{" "}
Fixed

2024-10-15 01:47 UTC, osaosula commented on src/pages/AddPatient.jsx
> +              </Grid>{" "}
Fixed

2024-10-15 01:48 UTC, osaosula commented on src/pages/AddPatient.jsx
> +              </Grid>{" "}
Fixed

2024-10-15 01:48 UTC, osaosula commented on src/pages/AddPatient.jsx
> +              </Grid>{" "}
Fixed

2024-10-15 14:43 UTC, osaosula commented on src/pages/AddPatient.jsx
> +              </Grid>{" "}
Fixed

2024-10-15 14:43 UTC, osaosula commented on src/pages/AddPatient.jsx
> +                  label="Mobile No"
Fixed

2024-10-15 19:55 UTC, BorisLaboratory approved these changes
Looks good

2024-10-16 13:53 UTC, merged